### ISSUE TITLE
"Cannot read property 'start' of null"

### ISSUE THREAD

**Issue by trisys3** [babel/babili#630]
Whenever I try to run `babel` with the full `babili` preset, I get an error from `babel-plugin-transform-remove-undefined`:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: app/app.js: Cannot read property 'start' of null
    at /path/to/project/node_modules/babel-plugin-transform-remove-undefined/lib/index.js:71:32
    at Array.some (native)
    at hasViolation (/path/to/project/node_modules/babel-plugin-transform-remove-undefined/lib/index.js:68:46)
    at PluginPass.VariableDeclaration (/path/to/project/node_modules/babel-plugin-transform-remove-undefined/lib/index.js:192:69)
    at newFn (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/path/to/project/node_modules/ec-core/node_modules/babel-traverse/lib/index.js:114:17)
```

I tried this with only `babel-preset-env` and `babili`. I am using so much ES6 that `esprima` does not know what to do without at least some plugins. I get "Invalid left-hand side in assignment".

I noticed that the referenced plugin, `babel-plugin-transform-remove-undefined`, is not in the list of plugins on the main `babili` README file, either in the main section or in the "Other" section, so I can just copy all the plugins in the main section and use the ones that I want from the "Other" section, and everything works fine. With npm 3, I can even do this without installing all the plugins individually, as long as I remember to install `babili` itself.

What is the plugin `transform-remove-undefined`, and why is it not in the plugin list on `babili`'s README file? Is it not finished or deprecated, or is it an internal plugin that `babili` always uses?

**Comment by vigneshshanmugam** [comment]
Hey, By default transform-remove-undefined is applied on the plugins list. 

Check the list of defaults here - https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options

**Comment by trisys3** [comment]
OK, I will try to get a minimal example running.

If `babel-plugin-transform-remove-undefined` is part of `babili`, why is it not documented on `babili`'s README? I am just wondering, as that seems like an omission.

**Comment by trisys3** [comment]
Versions:

babel-cli: 6.24.1
babili: 0.1.4
babel-preset-env: 1.6.0 (seems to be a conflict between `env` and `babili`)

.babelrc:

```
{
    'presets': [
        'env',
        'babili',
    ],
}
```

The smallest example I could get is:

```
const obj = {cat: 'dog'};

let cat;

({cat} = obj);
```

If I specify a value for `cat` at the start, I do not get the error:

```
const obj = {cat: 'dog'};

let cat = '';

({cat} = obj);
```


It seems to happen only if `cat` is not specified or is `undefined`; if I set `cat` to `null` at the start, or pretty much anything else, I do not get the error.

The error only shows up if I declare the variable beforehand then attempt to change it with destructuring; if I declare it and set it at the same time, using either `const` or `let`, I do not get the error:

```
const obj = {};
const {cat} = obj;
```

Obviously, now that I know why this is happening, I can easily avoid it by setting a value at the start, but this is still an unexpected, hard-to-track-down bug that should be fixed. If you need any more information, just ask.

**Comment by vigneshshanmugam** [comment]
Awesome, Thanks for the detailed writeup. Really helpful. Seems to be a bug still in master, Will have a look.

**Comment by trisys3** [comment]
No problem, glad I could help. Thanks for the great plugin and getting back so quickly!

**Comment by trisys3** [comment]
Looks like it works, thanks!
